### ISSUE TITLE
[Post list] Images are not compact in "compact" view

### ISSUE THREAD

**Issue by maltfield** [LiveFastEatTrashRaccoon/RaccoonForLemmy#127]
**Describe the bug**

I tried RacoonForLemmy, but I can't get it to display posts in a compact view. The images are enormous.

**To Reproduce**
1. Download latest from F-Droid
4. Immediately go to Hamburger Menu - > Settings because the default view is nearly useable (for viewing a list of posts)
5. Change "Content Appearance -> Post layout" to "Compact"
6. Go back
7. The posts aren't compact. I can still only see about 1.5-3 posts at a time.
8. Click around in the Settings for 30 minutes
9. Find no way to make the post listing useable
10. Open ticket

**Expected behavior**

I should be able to see 7-15+posts at at time (without scrolling) in "compact" view

If a post has an image attached, it should be visible, but it shouldn't make each row of the post larger. If a row without a picture is 50 pixels high, then the picture should be displayed 50 px high (and probably cropped to 50 pixels wide)

Consider RedReader, an app that was exempted from the reddit API change specifically because it has a highly accessible and accredited UI (a reference that we should strive to emulate):

**Screenshots**

| [![Screenshot of RedReader displaying 7 rows of posts on /r/aww](https://images.sftcdn.net/images/t_app-cover-l,f_auto/p/cc4d2ccb-cf77-4cc1-a6f3-aa14fd2ccc77/3137062875/redreader-screenshot.png)](https://images.sftcdn.net/images/t_app-cover-l,f_auto/p/cc4d2ccb-cf77-4cc1-a6f3-aa14fd2ccc77/3137062875/redreader-screenshot.png) |
|:--:| 
| RedReader's compact view is very compact! Note that posts with images display the image cropped and no taller than the rest of the posts' listings |

**Comment by AkesiSeli** [comment]
Thanks for the feedback, sorry for the inconvenience!

Does this look better? Unfortunately there is not much more I can do (and even like this at most 5 posts fit the screen)
![compact_posts](https://github.com/user-attachments/assets/baa78d4d-ed3b-4d64-aa20-7a5fd3d917e0)

**Comment by maltfield** [comment]
Thanks for fixing this :)
