### ISSUE TITLE
[Post list and Post itself] Media not loading fully

### ISSUE THREAD

**Issue by Mannivu** [LiveFastEatTrashRaccoon/RaccoonForLemmy#142]
**Describe the bug**
When opening a post that has a big/heavy image the app doesn't load it fully, but it loads a low-res version of it.

**To Reproduce**
1. Go to ['this post for example'](https://lemmy.dbzer0.com/post/32738717)
2. Click on the image

**Expected behavior**
The app should show a full resolution image, like Voyages does.
![image](https://github.com/user-attachments/assets/84b309ad-77f4-4915-b536-1d8c37b67c4b)

**Screenshots**
![image](https://github.com/user-attachments/assets/e3bbba9a-a5a4-44d7-8322-af496455a59d)

**Smartphone (please complete the following information):**
 - Device: Motorola Edge 50 Neo
 - OS: Android 14
 - Version 1.13.1

**Additional context**

**Comment by AkesiSeli** [comment]
Hi M.! Nice to hear from you back, even if it is for a bug! 🙈 And, again, a bug with image scaling 😂 

> Errare humanum est, perseverare autem diabolicum

Thanks for the report, I'll have a look into it as soon as I have time!
