### ISSUE TITLE
[Deep linking] Can't open links to comments

### ISSUE THREAD

**Issue by d-k-bo** [LiveFastEatTrashRaccoon/RaccoonForLemmy#145]
**Describe the bug**
When opening a URL that points to a comment, the application opens, but doesn't show the post and comment.

**To Reproduce**
1. Setup [Lemmy Redirect](https://github.com/zacharee/MastodonRedirect)
3. Open a link that points to a comment (e. g. https://feddit.org/comment/3292985)
4. The app opens and shows the default feed

**Expected behavior**
The app opens and shows the corresponding post and comment.

**Smartphone**
 - Device: Google Pixel 6
 - OS: Android 14 (LineageOS 21-20241202-NIGHTLY-oriole)
 - Version 1.13.1 (from f-droid.org)

**Additional context**
Looking at the source code, links to comments aren't handled at all: https://github.com/LiveFastEatTrashRaccoon/RaccoonForLemmy/blob/e28440225359d05cc7d91b4490d63afd8c2b7d3d/shared/src/commonMain/kotlin/com/livefast/eattrash/raccoonforlemmy/App.kt#L168-L189

**Comment by AkesiSeli** [comment]
I confirm, this is not implemented (yet) and the reason is that it was not trivial: opening a comment requires first reconstructing the post which is asynchronous then opening the post detail with the highlighted comment.

I thought this was a feature nobody would ever ask... well, until now 😂

**Comment by d-k-bo** [comment]
> I thought this was a feature nobody would ever ask... well, until now 😂

I guess my use case is somewhat specific :D 

For context, I run a bot that creates more or less funny comments. Each time the bot posts a comment, I get a push notification containing a link to the comment. From time to time, I want to take a look at these comments to see how well they are received.

**Comment by AkesiSeli** [comment]
I hope I'll be able to implement it (maybe leveraging the GET `/resolve_object` even in this case) because yours is a perfectly valid use case.
