### ISSUE TITLE
[Deep linking] Can't interact with posts opened via deep links

### ISSUE THREAD

**Issue by d-k-bo** [LiveFastEatTrashRaccoon/RaccoonForLemmy#146]
**Describe the bug**
When opening a URL that points to a post, the application opens and shows the post, but it isn't possible to vote or comment on the post. This affect both links from your instance and links from foreign instances.

**To Reproduce**
1. Setup [Lemmy Redirect](https://github.com/zacharee/MastodonRedirect)
3. Open a link that points to a post (e. g. https://feddit.org/post/5045633)
4. Try to vote or comment on the post
5. Nothing happens

**Expected behavior**
The vote button changes / a comment editor opens.

**Smartphone**
 - Device: Google Pixel 6
 - OS: Android 14 (LineageOS 21-20241202-NIGHTLY-oriole)
 - Version 1.13.1 (from f-droid.org)

**Comment by AkesiSeli** [comment]
Yes, I get it... posts are always opened in "guest mode" (i.e. no votes, no comments, no save etc.). There is a workaround to determine whether this is a local post (same instance where you are logged in) and only in that case allow actions, and I'll look into it.

Unfortunately, retrieving the "equivalent" of a foreign post through your instance is not trivial at all given Lemmy APIs to resolve contents, so for posts of other instances I really doubt anything can be done.

**Comment by d-k-bo** [comment]
> Unfortunately, retrieving the "equivalent" of a foreign post through your instance is not trivial at all given Lemmy APIs to resolve contents, so for posts of other instances I really doubt anything can be done.

AFAICT, this can be done using lemmy's `resolve_object` endpoint. If I search for a foreign post on my home instance, lemmy-ui uses this endpoint to find the post. The local URL for the post can then be constructed using its `id` field.

For example, to find https://lemmy.dbzer0.com/post/33036830 on my local instance https://feddit.org:

    curl -s 'https://feddit.org/api/v3/resolve_object?q=https%3A%2F%2Flemmy.dbzer0.com%2Fpost%2F33036830' | jq .post.post.id

returns `5510651`, which can be used to construct https://feddit.org/post/5510651, which is the local representation of the foreign post.

**Comment by AkesiSeli** [comment]
I have that call mapped and so far it was just used to resolve user and community handles, as far as I remember it did not work well with other kinds of entities (e.g. posts/comments).

I'll have a look at it because I've implemented a similar logic in "the other Raccoon" using Mastodon's GET `v2/search` endppoint with the `resolve` parameter to `true` which works great. And while I was doing it was thinking "I wish it was as easy as this on Lemmy!").
