### ISSUE TITLE
saving images bug

### ISSUE THREAD

**Issue by Totallynotmwa** [LiveFastEatTrashRaccoon/RaccoonForLemmy#151]
**Describe the bug**
When saving one image it saves multiple instead

**To Reproduce**
1. Go to 'image
2. Click on 'download'
3. Go on gallery 
4. See multiple images (sometimes more or less)

**Expected behavior**
Save only one image

**Screenshots**
![Screenshot_20241209_193226_Raccoon](https://github.com/user-attachments/assets/7e73f636-3ad7-43b3-9b60-b74a4590764c)
![Screenshot_20241209_193237_Gallery](https://github.com/user-attachments/assets/44938972-eaef-40d3-bacf-2e0a1183453b)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A55
 - OS: Android 14 
 - Version: 1.13.1

**Comment by AkesiSeli** [comment]
Can't reproduce but there are a couple of improvements which can be done:
- the "loading" state is not displayed in the UI, leading users to accidentally click more than once the button while the download is being done;
- the action buttons in the top bar do not have the correct size (and ripple effect).

I'll open a pull request to fix these issues. Thanks again for the report!

**Comment by Totallynotmwa** [comment]
> Can't reproduce but there are a couple of improvements which can be done:
> 
>     * the "loading" state is not displayed in the UI, leading users to accidentally click more than once the button while the download is being done;
> 
>     * the action buttons in the top bar do not have the correct size (and ripple effect).
> 
> 
> I'll open a pull request to fix these issues. Thanks again for the report!

It's fixed now yippee
