### ISSUE TITLE
Auto title not working

### ISSUE THREAD

**Issue by Mannivu** [LiveFastEatTrashRaccoon/RaccoonForLemmy#157]
When posting an URL post in a community, if I press the "AUTO" button to generate automatically a title I get a "Generic error" alert and no title is generated.

**Comment by AkesiSeli** [comment]
Thanks for reporting, I observed that the GET `api/v3/post/site_metadata` endpoint sometimes returns an empty object, depends on that is passed as a URL in the query string.

Since empty metadata is not technically an error, I'll use a different message.
