### ISSUE TITLE
Searching for content by URL

### ISSUE THREAD

**Issue by matj1** [LiveFastEatTrashRaccoon/RaccoonForLemmy#159]
**Is your feature request related to a problem? Please describe.**
I often want to open some content from Lemmy in a web browser in Raccoon for Lemmy. Opening the link in the app directly from the web browser is not possible, but many fediverse clients support that, if I put the URL of some fediverse content into the search bar, it finds the content.

**Describe the solution you'd like**
If I put a link to content on an instance of Lemmy to the search bar in Raccoon, it would show the content as the top result. It should work for posts, comments, users and communities.

**Describe alternatives you've considered**
Voyager for Lemmy has this feature, so I sometimes use that. But I like Raccoon more, and I would rather use only one client for Lemmy. 

How it looks in Voyager:
![Screenshot_20241212-150320_Voyager](https://github.com/user-attachments/assets/1f7f0ae2-54a8-43a2-adb3-4a4ffa8e7f4a)

**Comment by AkesiSeli** [comment]
I understand and this can be done, I confirm there is an API for that. I'll have a look at it as soon as I have time!
