### ISSUE TITLE
[Settings] Crash when opening Advanced settings

### ISSUE THREAD

**Issue by sabbaghpierre** [LiveFastEatTrashRaccoon/RaccoonForLemmy#192]
**Describe the bug**
App is crashing when clicking on Advanced settings.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Advanced settings'

**Smartphone (please complete the following information):**
 - Device: Samsung A14
 - OS: Android 14
 - One UI: 6.1

**Comment by AkesiSeli** [comment]
My bad, there was another dependency injection misconfiguration. Thanks a lot for the report, I'll release another hotfix soon.
